# Runs on a single g3.16xl node
atari-apex:
    env:
        grid_search:
            - BreakoutNoFrameskip-v4
            - BeamRiderNoFrameskip-v4
            - QbertNoFrameskip-v4
            - SpaceInvadersNoFrameskip-v4 
    run: APEX
    config:
        target_network_update_freq: 50000
        num_workers: 12
        num_envs_per_worker: 5
        sample_batch_size: 53
        lr: .0001
        gamma: 0.99
