# Runs on a single g3.16xl node
atari-dqn:
    env:
        grid_search:
            - BreakoutNoFrameskip-v4
            - BeamRiderNoFrameskip-v4
            - QbertNoFrameskip-v4
            - SpaceInvadersNoFrameskip-v4 
    run: DQN
    config:
        gpu: True
        gamma: 0.99
        lr: .0001
        learning_starts: 10000
        buffer_size: 50000
        sample_batch_size: 4
        train_batch_size: 32
        schedule_max_timesteps: 2000000
        exploration_final_eps: .01
        exploration_fraction: .1
