pong-apex:
    env: CartPole-v0
    run: DQN
    resources:
        cpu:
            eval: spec.config.num_workers
        gpu: 0
        driver_cpu_limit: 1
    stop:
        episode_reward_mean: 200
    config:
        num_workers: 2
        n_step: 3
        gamma: 0.99
        lr: .001
        learning_starts: 1000
        buffer_size: 10000
        target_network_update_freq: 500
        sample_batch_size: 4
        max_weight_sync_delay: 4
        train_batch_size: 32
        timesteps_per_iteration: 100
        apex_optimizer: True
        per_worker_exploration: True
        worker_side_prioritization: True
        num_replay_buffer_shards: 2
        num_gradient_worker_shards: 0
        min_train_to_sample_ratio: 0.75
        num_gpus_per_grad_worker: 0
