pong-v0:
    env: Pong-v0
    run: DQN
    resources:
        cpu: 1
        gpu: 1
    config:
        gamma: 0.99
        lr: .0001
        n_step: 3
        buffer_size: 2000000
        schedule_max_timesteps: 2000000
        sample_batch_size: 4
        learning_starts: 100
        target_network_update_freq: 1000
        train_batch_size: 32
        exploration_final_eps: .01
        exploration_fraction: .1
        model:
          grayscale: True
