pong-apex:
    env: PongDeterministic-v4
    run: DQN
    resources:
        cpu:
            eval: spec.config.num_workers
        gpu: 1
        driver_cpu_limit: 1
    stop:
        episode_reward_mean: 20
        time_total_s: 7200
    config:
        num_workers: 128
        gamma: 0.99
        lr: .0001
        learning_starts: 1000  # TODO(ekl) increase to 50k
        buffer_size: 250000
        target_network_update_freq: 1280000
        sample_batch_size: 400
        max_weight_sync_delay: 400
        train_batch_size: 512
        apex_optimizer: True
        timesteps_per_iteration: 5000
        per_worker_exploration: True
        worker_side_prioritization: True
        model:
          grayscale: True
          zero_mean: False
          dim: 42
          conv_filters: [
              [16, [4, 4], 2],
              [32, [4, 4], 2],
              [512, [11, 11], 1],
          ]
