pong-apex:
    env: Pong-v0
    run: DQN
    resources:
        cpu:
            eval: spec.config.num_workers
        gpu: 9
        driver_cpu_limit: 1
        driver_gpu_limit: 1
    stop:
        episode_reward_mean: 20
    config:
        num_workers: 32
        n_step: 3
        gamma: 0.99
        lr: .0001
        learning_starts: 50000
        buffer_size: 250000
        target_network_update_freq: 1280000
        sample_batch_size: 50
        max_weight_sync_delay: 400
        train_batch_size: 512
        apex_optimizer: True
        timesteps_per_iteration: 25000
        per_worker_exploration: True
        worker_side_prioritization: True
        num_replay_buffer_shards: 4
        num_gradient_worker_shards: 0
        num_gpus_per_grad_worker: 1
        min_train_to_sample_ratio: 0.75
        model:
          grayscale: True
