pong-apex:
    env: PongNoFrameskip-v4
    run: APEX
    resources:
        cpu:
            eval: spec.config.num_workers
        gpu: 1
    config:
        force_evaluators_remote: True  # requires cluster
        num_workers: 128
        lr: .0001
        gamma: 0.99
