pong-bgapex:
    env: PongNoFrameskip-v4
    run: APEX
    repeat: 2
    resources:
        cpu:
            eval: spec.config.num_workers
        gpu: 1
    config:
        force_evaluators_remote: True  # requires cluster
        target_network_update_freq: 50000
        num_workers: 8
        num_background_prio_workers:
            grid_search: [0, 50]
        lr: .0001
        gamma: 0.99

