pong-apex:
    env: PongNoFrameskip-v4
    run: DQN
    resources:
        cpu:
            eval: spec.config.num_workers
        gpu: 1
    config:
        num_workers: 64
        lr: .0001
        n_step: 3
        gamma: 0.99
        learning_starts: 50000
        buffer_size: 2000000
        target_network_update_freq: 50000
        sample_batch_size: 50
        max_weight_sync_delay: 400
        train_batch_size: 512
        apex_optimizer: True
        timesteps_per_iteration: 25000
        num_replay_buffer_shards: 4
        force_evaluators_remote: True
        model:
          grayscale: True
