pong-apex:
    env: PongNoFrameskip-v4
    run: DQN
    run: APEX
    resources:
        cpu:
            eval: spec.config.num_workers
        gpu: 1
    config:
        num_workers: 128
        force_evaluators_remote: True  # requires cluster
        lr: .0001
        gamma: 0.99
        target_network_update_freq: 50000
        train_batch_size: 32
        model:
          grayscale: True
