pong-apex:
    env: PongNoFrameskip-v4
    run: DQN
    run: APEX
    resources:
        cpu:
            eval: spec.config.num_workers
        gpu: 1
    config:
        num_workers: 32
        force_evaluators_remote: True  # requires cluster
        lr: .0001
        gamma: 0.99
        target_network_update_freq: 500000
        train_batch_size: 512
        prioritized_replay_beta:
            grid_search: [0.4, 1.0]
        prioritized_replay_alpha:
            grid_search: [0.6, 1.0]
