cluster_name: default
min_workers: 3
max_workers: 3
target_utilization_fraction: 0.8
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a
auth:
    ssh_user: ubuntu

head_node:
    InstanceType: m5.large
    ImageId: ami-0888a3b5189309429  # DLAMI 7/1/19
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
              VolumeSize: 150

worker_nodes:
    InstanceType: m5.large
    ImageId: ami-0888a3b5189309429  # DLAMI 7/1/19
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
              VolumeSize: 150

# List of shell commands to run to set up nodes.
setup_commands:
    # Install latest TensorFlow
    - source activate tensorflow_p36 && conda remove -y --force wrapt || true
    - source activate tensorflow_p36 && pip install -U tensorflow==1.14
    # Install nightly Ray wheels.
    # Example: https://s3-us-west-2.amazonaws.com/ray-wheels/<<<RAY_BRANCH>>>/<<<RAY_COMMIT>>>/ray-<<<RAY_VERSION>>>-cp36-cp36m-manylinux1_x86_64.whl
    - source activate tensorflow_p36 && pip install -U RAY_WHEEL_TO_TEST_HERE - source activate tensorflow_p36 && pip install ray[rllib] ray[debug] gym[atari]
    - source activate tensorflow_p36 && pip install ray[debug]
    - echo set-window-option -g mouse on > ~/.tmux.conf
    - echo 'termcapinfo xterm* ti@:te@' > ~/.screenrc

    # Uncomment the following if you wish to build Ray instead.
    # - sudo apt-get update
    # - sudo apt-get install -y build-essential curl unzip
    # - git clone https://github.com/ray-project/ray || true
    # - ray/ci/travis/install-bazel.sh
    # - cd ray/python; git checkout master; git pull; source activate tensorflow_p36 && pip install -e . --verbose

head_start_ray_commands:
    - source activate tensorflow_p36 && ray stop
    - ulimit -n 65536; source activate tensorflow_p36 && ray start --head --redis-port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - source activate tensorflow_p36 && ray stop
    - ulimit -n 65536; source activate tensorflow_p36 && ray start --redis-address=$RAY_HEAD_IP:6379 --object-manager-port=8076
